[project]
name = "coingeckoapi-etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<=3.12"
dependencies = [
    "apache-airflow>=3.1.8",
    "asyncpg>=0.31.0",
    "graphviz>=0.21",
    "pandas>=2.3.3",
    "pre-commit>=4.5.1",
    "requests>=2.33.0",
    "sqlalchemy>=2.0.48",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["coingecko"]
